export const MAX_STUDENTS_PER_ROOM = 30;
export const MAX_BITRATE_PER_TRANSPORT = 1_500_000;
export const MIN_BITRATE_PER_TRANSPORT = 100_000;
export const PRESENCE_BROADCAST_INTERVAL_MS = 30_000;
export const JOIN_CODE_LENGTH = 6;
